name: GPT PR Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gpt-review:
    name: Run GPT Code Reviewer
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, '리뷰')
    steps:
      - uses: Gotkwondo/ChatGPT_Auto_CodeReviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
